# Generated by Django 5.2.3 on 2025-06-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdctColor',
            new_name='ProductColor',
        ),
    ]
