# Generated by Django 5.2.3 on 2025-06-16 00:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('white', 'white'), ('brown', 'brown'), ('cyan', 'cyan'), ('black', 'black')], max_length=20), size=10),
        ),
    ]
