# Generated by Django 5.2.3 on 2025-06-18 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Power', 'Power'), ('Velvet', 'Velvet'), ('Sleek', 'Sleek'), ('Drift', 'Drift'), ('Wool', 'Wool'), ('Heritage', 'Heritage'), ('Phantom', 'Phantom')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%M/%D'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='inventory.tags'),
        ),
    ]
