# Generated by Django 5.2.3 on 2025-06-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_tags_product_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='tags',
        ),
    ]
